name: Deploy Gatsby Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: node
        uses: actions/setup-node@v4
        with:
            node-version: 16
            registry-url: https://registry.npmjs.org
      - name: npm install, build, and csv
        run: |
          npm install
          npm run build
          npm run csv
      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
